baseURL = 'https://lumramabaja.com/'
languageCode = 'en-us'
title = 'Lum Ramabaja'
theme = 'mini'
publishDir = 'public'
defaultContentLanguage = 'en'
hasCJKLanguage = true
[pagination]
  pagerSize = 4
disqusShortname = 'Lum Ramabaja'

[permalinks]
  posts = '/posts/:title/'

[services]
  [services.googleAnalytics]
    id = 'your-google-analytics-id'

[markup]
  [markup.highlight]
    guessSyntax = true
    style = 'dracula'
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  [social]
    github = 'https://github.com/ChainlessCoder'
  avatarLink = 'https://github.com/ChainlessCoder'
  author = 'Lum Ramabaja'
  description = 'My Blog'
  enableRSS = true
  enableComments = true
  enableGoogleAnalytics = true
  showToc = true
  customCSS = ["css/custom.css"]
  showPowerBy = false
  math = true
  hiddenPostSummaryInHomePage = false